spring.application.name=1_SpringBoot

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=SPRINGBOOT
spring.datasource.password=SPRINGBOOT

#타임리프 설정
spring.thymeleaf.cache=false

#mybatis
#mybatis.mapper-locations=classpath:mappers/member-mapper.xml, classpath:mappers/board-mapper.xml
mybatis.mapper-locations=classpath:mappers/**.xml
mybatis.configuration.map-underscore-to-camel-case=true
#mybatis.type-aliases-package=kh.springboot.member.model.vo, kh.springboot.board.model.vo
mybatis.type-aliases-package=kh.springboot.*.model.vo
mybatis.configuration.jdbc-type-for-null=null

#mail
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=guswhd3666@gmail.com
spring.mail.password=xjwj mocl vbtx mfjt